@startuml
skinparam componentStyle rectangle
package "cli" {
  [cli_display]
  [cli_habit_management]
  [cli_goal_management]
  [cli_category_management]
  [cli_analysis]
  [cli_export]
  [cli_utils]
}
package "core" {
  [habit]
  [category]
  [goal]
  [completion]
}
package "db" {
  [momentum_db]
}
package "analysis" {
  [habit_analysis]
}
package "utils" {
  [momentum_utils]
  [error_manager]
  [encouragements]
}
package "main" {
  [momentum_main]
  [momentum_cli]
}
[category] --> [momentum_db]
[cli_analysis] --> [momentum_utils]
[cli_analysis] --> [habit_analysis]
[cli_analysis] --> [momentum_db]
[cli_category_management] --> [category]
[cli_category_management] --> [momentum_utils]
[cli_category_management] --> [error_manager]
[cli_category_management] --> [momentum_db]
[cli_display] --> [momentum_utils]
[cli_display] --> [momentum_db]
[cli_export] --> [momentum_utils]
[cli_export] --> [momentum_db]
[cli_goal_management] --> [goal]
[cli_goal_management] --> [momentum_utils]
[cli_goal_management] --> [error_manager]
[cli_goal_management] --> [momentum_db]
[cli_habit_management] --> [encouragements]
[cli_habit_management] --> [momentum_utils]
[cli_habit_management] --> [error_manager]
[cli_habit_management] --> [habit]
[cli_habit_management] --> [momentum_db]
[cli_utils] --> [momentum_utils]
[completion] --> [momentum_db]
[goal] --> [momentum_db]
[habit] --> [error_manager]
[habit_analysis] --> [momentum_db]
[momentum_cli] --> [encouragements]
[momentum_cli] --> [cli_analysis]
[momentum_cli] --> [momentum_utils]
[momentum_cli] --> [error_manager]
[momentum_cli] --> [cli_export]
[momentum_cli] --> [cli_display]
[momentum_cli] --> [habit_analysis]
[momentum_cli] --> [cli_goal_management]
[momentum_cli] --> [cli_category_management]
[momentum_cli] --> [habit]
[momentum_cli] --> [momentum_db]
[momentum_cli] --> [cli_habit_management]
[momentum_cli] --> [cli_utils]
[momentum_db] --> [category]
[momentum_db] --> [goal]
[momentum_db] --> [habit]
[momentum_main] --> [momentum_db]
[seed_data] --> [category]
[seed_data] --> [goal]
[seed_data] --> [habit]
[seed_data] --> [momentum_db]
@enduml